# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="robbyrussell"
#export ZSH_THEME="sporty_256"
# export ZSH_THEME="Soliah"
# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
 export DISABLE_AUTO_UPDATE="true"

 #Uncomment following line if you want to disable colors in ls
 #export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git heroku redis-cli rails4 postgres github brew bundler osx )
#plugins=(git heroku redis-cli postgres github brew osx )
plugins=(git tmux brew osx bundler)

source $ZSH/oh-my-zsh.sh
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
eval "$(direnv hook zsh)"
alias tmux="TERM=screen-256color-bce tmux"
#export PATH=/usr/local/bin:/usr/local/sbin:$PATH
# Customize to your needs...
#export EDITOR="mvim -f"
#eval `direnv hook $0`
#autoload bashcompinit
#bashcompinit
#source /usr/local/etc/bash_completion.d/rabbitmqadmin.bash
